x-common: &common
  privileged: true
  volumes:
    - source: ./
      target: /src
      type: bind

services:
  debian:
    build: &build
      dockerfile: Dockerfile
      args:
        OS: debian:latest
    image: andyneff/hello-world-gdb:debian
    <<: *common

  ubuntu:
    build:
      <<: *build
      args:
        OS: ubuntu:22.04
    image: andyneff/hello-world-gdb:ubuntu
    <<: *common

  alpine:
    build:
      <<: *build
      args:
        OS: alpine:latest
    image: andyneff/hello-world-gdb:alpine
    <<: *common